-- Enhanced Kinklist :: Postgres schema (legacy app, post-migration)
--
-- Differences from create_db_mysql.sql, all deliberate:
--   * users is merged into answers as the `submitter` JSONB column.
--   * `user` (a Postgres reserved word) becomes `user_uuid`.
--   * hits and stats are dropped; the stats compiler is retired.
--   * No IP address is stored anywhere.
--   * JSON columns become JSONB.

CREATE TABLE IF NOT EXISTS choices (
    id   INTEGER     NOT NULL PRIMARY KEY,
    name VARCHAR(60) NOT NULL
);

-- Reference data only: the legacy 11-value answer scale. Retained as
-- provenance for any future mapping onto the Kinklist v2 answer set.
INSERT INTO choices(id, name) VALUES
    (-1, 'Confused'),
    (0,  'Not applicable/entered'),
    (1,  'Have tried - Favorite'),
    (2,  'Have tried - Liked'),
    (3,  'Have tried - Was okay'),
    (4,  'Have tried - Didn''t like'),
    (5,  'Have tried - Hated'),
    (6,  'Haven''t tried - Would love to try'),
    (7,  'Haven''t tried - Would want to try'),
    (8,  'Haven''t tried - Indifferent to it'),
    (9,  'Haven''t tried - Might try'),
    (10, 'Haven''t tried - Won''t ever try')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS answers (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token            VARCHAR(64) NOT NULL,
    "timestamp"      BIGINT      NOT NULL,
    choices_json     JSONB       NOT NULL,
    hit_count        INTEGER     NOT NULL DEFAULT 0,
    catalog_id       VARCHAR(64) NOT NULL DEFAULT 'main',
    catalog_version  VARCHAR(64) NOT NULL DEFAULT 'legacy',
    max_spice_level  SMALLINT    NULL,
    shown_item_ids   JSONB       NULL,
    answer_context   VARCHAR(64) NOT NULL DEFAULT 'realistic_adult_partner',
    partner_personas JSONB       NULL,

    -- Merged from the old users table.
    -- user_uuid links repeat submissions from the same browser.
    -- submitter holds username/sex/age/fap_freq/sex_freq/body_count as a
    -- point-in-time snapshot per submission. It never holds an IP address.
    user_uuid        VARCHAR(36) NULL,
    submitter        JSONB       NOT NULL DEFAULT '{}'::jsonb,

    -- Provenance from the MySQL import; NULL for rows created after cutover.
    legacy_user_id   INTEGER     NULL,

    CONSTRAINT answers_token_key UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS answers_user_uuid_idx  ON answers (user_uuid);
CREATE INDEX IF NOT EXISTS answers_catalog_idx    ON answers (catalog_id, catalog_version);
-- Watermark index for the incremental migration delta pass.
CREATE INDEX IF NOT EXISTS answers_timestamp_idx  ON answers ("timestamp");

CREATE TABLE IF NOT EXISTS catalog_snapshots (
    catalog_id      VARCHAR(64) NOT NULL,
    catalog_version VARCHAR(64) NOT NULL,
    data            JSONB       NOT NULL,
    created         BIGINT      NOT NULL,
    PRIMARY KEY (catalog_id, catalog_version)
);

CREATE TABLE IF NOT EXISTS suggestions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp" BIGINT       NOT NULL,
    suggestion  TEXT         NOT NULL,
    -- md5(timestamp || suggestion). The legacy table has no primary key, so
    -- this is what makes re-running the migration idempotent. A btree unique
    -- index on the TEXT column itself would hit the 2704-byte limit.
    legacy_digest CHAR(32)   NOT NULL,
    CONSTRAINT suggestions_legacy_digest_key UNIQUE (legacy_digest)
);

CREATE INDEX IF NOT EXISTS suggestions_timestamp_idx ON suggestions ("timestamp");

CREATE TABLE IF NOT EXISTS error_logs (
    -- id is carried over from MySQL so re-runs conflict instead of duplicating.
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "timestamp" BIGINT      NOT NULL,
    error_type  VARCHAR(64) NOT NULL,
    message     TEXT        NOT NULL,
    user_agent  VARCHAR(512) NULL,
    data        JSONB       NULL
);

CREATE INDEX IF NOT EXISTS error_logs_timestamp_idx ON error_logs ("timestamp");
CREATE INDEX IF NOT EXISTS error_logs_type_idx      ON error_logs (error_type);
